### ISSUE TITLE
iGenomes parameters aren't picked up

### ISSUE THREAD

**Issue by pageale** [DIncalciLab/samurai#19]
### Description of the bug

Hello !!
First of all, thank you for sharing this interesting pipeline.
I tried to download it and I experimented some issues in the first steps for trying to run it.

I got this error:
`
------------------------------------------------------
WARN: The following invalid input values have been detected:

* --filter_bam_pon: false

ERROR ~ Argument of `file` function cannot be null

 -- Check script '/home/a/.nextflow/assets/dincalcilab/samurai/./workflows/samurai.nf' at line: 75 or see '.nextflow.log' file for more details
`

I am not sure if it is due because I didn't make any modication in the .config file or I made an error when adding it into singularity.

I will wait for your reply and thank you in advance !

### Command used and terminal output

```console
nextflow run dincalcilab/samurai --input test4samples.csv --outdir test2 --genome GRCh38 -profile test,singularity

nextflow run dincalcilab/samurai -profile test,singularity --outdir test1
```

### System information

N E X T F L O W  ~  version 23.10.1
Container: Singularity
OS: Linux
? Select release / branch: v1.0.2  [release]
dincalcilab/samurai v1.0.2-gcbb0cc7

**Comment by lbeltrame** [comment]
Hello, and thanks for checking out SAMURAI! Sorry for the delay, I didn't get any mail for the bug. 
Can you share at least one or two lines of the samplesheet if you can?

**Comment by lbeltrame** [comment]
For now don't use profiles `test` or `test_full` as the tests are still a problem (https://github.com/DIncalciLab/samurai/issues/6). 
Can you try running this just with the `singularity` profile and see what happens?

**Comment by pageale** [comment]
Hello again! thank you for replying !

I have just ran both alternatives and the error still persists:
`
nextflow run dincalcilab/samurai --input test4samples.csv --outdir test2 --genome GRCh38 -profile singularity
`

`
nextflow run dincalcilab/samurai --input test4samples.csv --outdir test2 --genome GRCh38 -profile singularity --igenomes_base s3://ngi-igenomes/igenomes
`
Below, i provide some screenshot in case that they could be helpful.

![image](https://github.com/user-attachments/assets/17d8b77f-956b-4629-96af-817047a75a24)

![image](https://github.com/user-attachments/assets/4780d426-37a1-4988-981b-b2547222a0c4)


this is the sample sheet I use as input
![image](https://github.com/user-attachments/assets/f445e075-f1ba-48aa-bcfe-b4e7f4510844)

By the way, I would like to confirm something, do i have to modify something in the nextflow files? I mean, just after downloading or adding the pipeline to singulairty.

Thanks you so much !

**Comment by lbeltrame** [comment]
OK, so this confirms the issue

1. iGenomes files weren't downloaded;
2. If you don't have a FASTA file specified (which happens because of 1) the pipeline does not check for it and breaks

Can you upload here the `.nextflow.log` file which is generated in the same folder as where you ran the pipeline? Technically iGenomes download should happen "out of the box".

**Comment by lbeltrame** [comment]
Also, can you update now (`nextflow pull DIncalciLab/samurai`) and see whether the pipeline at least throws an error? This doesn't fix the issue but at least makes the error more understandable.

**Comment by pageale** [comment]
Hello ! this is the `.nextflow.log` file
[nextflow.log](https://github.com/user-attachments/files/17379538/nextflow.log)

and the pull does not give any errors
`
nextflow pull DIncalciLab/samurai
Checking DIncalciLab/samurai ...
 Already-up-to-date -
`

**Comment by lbeltrame** [comment]
Nothing out of ordinary in the logs. I'm going to try and test this with a minimal case.

**Comment by lbeltrame** [comment]
Ok, I found the reason, and it's actually a problem of how Nextflow loads its resources (cf: https://github.com/nf-core/tools/pull/2828). I pushed something that *may* fix it, but I havent' tested it yet.

**Comment by pageale** [comment]
Thank you !!

I have just download the new version v1_0_3 and the output changed (image below). Should i provide a local fasta reference? 


![image](https://github.com/user-attachments/assets/dcfb4e32-97fc-4222-80c6-af02901c3dd7)

**Comment by lbeltrame** [comment]
If you can please provide again the .nextflow.log and also the full command line you used to run SAMURAI it would be hepful.
I ask because at this point I just ran a minimal example to make sure it would work and it went through (modulo some small adjustments I already pushed). 

```
nextflow run DIncalciLab/swgscna -r master --input samplesheet.minimal.csv --outdir ./trash -profile singularity --analysis_type align_only --genome hg38 --aligner bwamem
```

**Comment by pblpez** [comment]
Hello!
I was following this issue as I was having the same error. After last push I don't get any error anymore, however the run stops right after it starts, without outputting any error.

This is the command I ran:
`nextflow run samurai --input /media/nas252/OMICS/CNA/samurai/004_0256_CRC_AA_bam_paths.csv --outdir /media/nas252/OMICS/CNA/samurai/output --genome GRCh38 --binsize 1000000 --pon_path /media/nas252/OMICS/CNA/1000000/PoN_004_0256_sWGS_no_dedup_1000000_median.rds --ichorcna_readcounter_chrs "c(1:22)" --ichorcna_chrs_to_use "c(1:22)" --ichorcna_chrs_to_train "c(1:22)" --ichorcna_chrs_to_normalize "c(1:22)" --ichorcna_gc_wig /media/nas252/OMICS/CNA/gc_map_wigfiles/grch38/GRCh38.gc.ws_1000000.wig --ichorcna_map_wig /media/nas252/OMICS/CNA/gc_map_wigfiles/grch38/GRCh38.map.ws_1000000.wig --ichorcna_centromere_file /home/pperez/ichorCNA/inst/extdata/GRCh38.GCA_000001405.2_centromere_acen.txt -profile docker `

These are the logs from samurai and nextflow:
[samurai_log.txt](https://github.com/user-attachments/files/17409780/samurai_log.txt)
[nextflow.log](https://github.com/user-attachments/files/17409787/nextflow.log)

Thank you for your help and for providing this interesting pipeline!

**Comment by lbeltrame** [comment]
Hello there,

I have a hunch for this, and it might be unrelated (but still a bug). Can you run this with `--analysis_type liquid_biopsy --caller ichorcna`?

*If* it runs, regardless of this erroring or not, please open a new issue mentioning a lack of default for `analysis_type` and we'll take it from there. If not, we'll see.

Apologies if the documentation is unclear, there hasn't been enough time to update it.

**Comment by pblpez** [comment]
Hi again and thank you for the quick reply.
I've added those parameters:
`nextflow run samurai --input /media/nas252/OMICS/CNA/samurai/004_0256_CRC_AA_bam_paths.csv --outdir /media/nas252/OMICS/CNA/samurai/output --genome GRCh38 --binsize 1000000 --analysis_type liquid_biopsy --caller ichorcna --pon_path /media/nas252/OMICS/CNA/1000000/PoN_004_0256_sWGS_no_dedup_1000000_median.rds --ichorcna_readcounter_chrs "c(1:22)" --ichorcna_chrs_to_use "c(1:22)" --ichorcna_chrs_to_train "c(1:22)" --ichorcna_chrs_to_normalize "c(1:22)" --ichorcna_gc_wig /media/nas252/OMICS/CNA/gc_map_wigfiles/grch38/GRCh38.gc.ws_1000000.wig --ichorcna_map_wig /media/nas252/OMICS/CNA/gc_map_wigfiles/grch38/GRCh38.map.ws_1000000.wig --ichorcna_centromere_file /home/pperez/ichorCNA/inst/extdata/GRCh38.GCA_000001405.2_centromere_acen.txt -profile docker `

This time it took a bit longer to stop, but it did again few seconds after starting.
[nextflow.log](https://github.com/user-attachments/files/17410410/nextflow.log)

I am not sure if the parameters provided are in the right format or something is missing. I have doubts with some parameters like "normal_panel" as I already specify the PoN file with --pon_path.

 I tried to run also with default parameters (just providing the input) and got the same outcome. My input is a csv with two columns "sample" and "bam", containing the sampleIDs and paths to the bam files from only cancer samples.

Thanks again!

**Comment by lbeltrame** [comment]
First let me explain the ambiguity (yeah, docs *really* need to get written):

- `--normal_panel` is when you already have a panel of normals
- `--pon_path` is to point at BAM files to create a PoN: it has no effect unless `--build_pon` is specified as well 

Secondly I stumbled on this line from the log:

```
Oct-17 12:05:33.198 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
```

It seems that Nextflow isn't finding something to execute it on. I can try to reproduce this, but at the present time our compute platform is a bit pressed for resources so I'm not sure if I'll get to it quickly. 

I assume you run other Nextflow / nf-core pipelines without hitch?

**Comment by lbeltrame** [comment]
I've pushed a change, can you pull and try? I don't think this addresses the problem but worth trying. For the record the pipeline with the `docker` executor starts here.

**Comment by pblpez** [comment]
Hi, I ran it again before last commit. I specified the PoN correctly this time (in --normal_panel) and it started running for a while. I will pull the last version and try again with a similar configuration. I guess that if it stops again it might be a local problem.

Thank you for your help!

**Comment by lbeltrame** [comment]
If you find different problems, feel free to open separate issues: I might not be able to look at them, but at least they'll stay there tracked.

**Comment by pageale** [comment]
> If you can please provide again the .nextflow.log and also the full command line you used to run SAMURAI it would be hepful. I ask because at this point I just ran a minimal example to make sure it would work and it went through (modulo some small adjustments I already pushed).
> 
> ```
> nextflow run DIncalciLab/swgscna -r master --input samplesheet.minimal.csv --outdir ./trash -profile singularity --analysis_type align_only --genome hg38 --aligner bwamem
> ```
> 
> This screams for automated testing, but I don't think it's even possible to do that on GH...

Hello !!

Sorry for the late reply.. 
I will attach here the command and log file

`
nextflow run DIncalciLab/samurai -r v1.0.3 --input test4samples.csv --outdir test2 --genome GRCh38 -profile singularity --genome hg38 --aligner bwamem --analysis_type liquid_biopsy --caller ichorcna

`
`
nextflow pull DIncalciLab/samurai
Checking DIncalciLab/samurai ...
 done - revision: 1f8cf74d75 [v1.0.3]
`

[nextflow.log](https://github.com/user-attachments/files/17437705/nextflow.log)


Thank u in advance !!

**Comment by lbeltrame** [comment]
It wouldn't hurt to try and update and see whether it persists. It's very "interesting" in the sense that everything is set as it should, but... it doesn't seem to progress. 
I will try again to see if I can reproduce this.

**Comment by pageale** [comment]
Hello ! I tried another approach, instead of using the singularity container I changed to docker (as @pblpez put as profile in his command) and now the IGenomes parameters are reconigsed. 

I leave this comment in case that it might be helpful !
