### ISSUE TITLE
img2pdf: error: unrecognized arguments: -c eval export PYTHONNOUSERSITE="1" 

### ISSUE THREAD

**Issue by pageale** [DIncalciLab/samurai#28]
### Description of the bug

Hello !
I hope you all are having a good day !
I was encountering an issue where the img2pdf command in the CONVERT_WISECONDORX_IMAGES. I found a related comment in the GitHub issues section [here](https://github.com/DIncalciLab/samurai/issues/25#issuecomment-2446260905), which seems to mention a similar problem.) .I have tried a few potential solutions, such as unsetting environment variables only for this specific process, but the error persists.

![image](https://github.com/user-attachments/assets/f5589f32-8779-4445-bd3b-547236be5e03)

```console
-[dincalcilab/samurai] Pipeline completed with errors-
ERROR ~ Error executing process > 'DINCALCILAB_SAMURAI:SAMURAI:LIQUID_BIOPSY:CONVERT_WISECONDORX_IMAGES (genome_plot)'

Caused by:
  Process `DINCALCILAB_SAMURAI:SAMURAI:LIQUID_BIOPSY:CONVERT_WISECONDORX_IMAGES (genome_plot)` terminated with an error exit status (2)

Command executed:

  img2pdf A_genome_plot.png B_genome_plot.png C_genome_plot.png D_genome_plot.png \
      --title "WisecondorX results" \
      -o genome_plots.pdf
  
  cat <<-END_VERSIONS > versions.yml
  "DINCALCILAB_SAMURAI:SAMURAI:LIQUID_BIOPSY:CONVERT_WISECONDORX_IMAGES":
      img2pdf: $(img2pdf --version | cut -d' ' -f2)
  END_VERSIONS

Command exit status:
  2

Command output:
  (empty)

Command error:
  usage: img2pdf [-h] [-v] [-V] [--gui] [-o out] [-C colorspace] [-D]
                 [--engine engine] [--first-frame-only] [--pillow-limit-break]
                 [--pdfa [PDFA]] [-S LxL] [-s LxL] [-b L[:L]] [-f FIT] [-a]
                 [--crop-border L[:L]] [--bleed-border L[:L]]
                 [--trim-border L[:L]] [--art-border L[:L]] [--title title]
                 [--author author] [--creator creator] [--producer producer]
                 [--creationdate creationdate] [--moddate moddate]
                 [--subject subject] [--keywords kw [kw ...]]
                 [--viewer-panes PANES] [--viewer-initial-page NUM]
                 [--viewer-magnification MAG] [--viewer-page-layout LAYOUT]
                 [--viewer-fit-window] [--viewer-center-window]
                 [--viewer-fullscreen]
                 [infile ...]
  img2pdf: error: unrecognized arguments: -c eval export PYTHONNOUSERSITE="1"
  export R_PROFILE_USER="/.Rprofile"
  export R_ENVIRON_USER="/.Renviron"
  export JULIA_DEPOT_PATH="/usr/local/share/julia"
  export PATH="$PATH:/home/.nextflow/assets/dincalcilab/samurai/bin"; /bin/bash .command.run nxf_trace

```

might it be arguments being passed to the img2pdf container from the Docker image itself? I attach the command.sh and log files below

PD: Additionally, I encountered the error related to an unsupported genome when using GRCh38 with GISTIC. To resolve that, I made a small modification locally to the genome switch statement in the script to ensure GRCh38 is recognized and treated the same as hg38:

```console
switch(genome) {
        case "hg38":
        case "GRCh38":
            ref_gene_file = "-refgene '/opt/refgenefiles/hg38.UCSC.add_miR.160920.refgene.mat'"
            break
        case "hg19":
            ref_gene_file = "-refgene '/opt/refgenefiles/hg19.UCSC.add_miR.140312.refgene.mat'"
            break
        default:
            error "Unsupported genome ${genome}"
    }
```

Looking forward for your reply!
Thanks in advance!

### Command used and terminal output

```console
nextflow run dincalcilab/samurai --input test4bams.csv -profile docker \
--outdir test_docker_samurai --genome GRCh38 \
--fasta ~/Reference/bwa_GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa     \
--fai ~/Reference/bwa_GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.fai     \
--dict ~/Reference/bwa_GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.dict \
--analysis_type liquid_biopsy --caller wisecondorx \
--normal_panel /home/alessandra/Projects/rawdata/test_docker_samurai/wisecondorx/PoN/PoN.npz \
--max_memory 28.GB --compute_signatures TRUE --run_gistic TRUE --gistic_broad_analysis TRUE
```

### Relevant files

N E X T F L O W ~ version 23.10.1
Container: Docker
OS: Linux
Version: dincalcilab/samurai v1.0.3-gf92d1e1

### System information

[command_24nov.txt](https://github.com/user-attachments/files/17905367/command_24nov.txt)

[nextflow24nov.log](https://github.com/user-attachments/files/17905397/nextflow24nov.log)

**Comment by lbeltrame** [comment]
Thanks for the report! Can you provide the `.command.sh` in the workdir mentioned by Nextflow? The error is kind of nonsense (it's like something wrong is passed to img2pdf), so I have to figure out what's going on.

Please file a separate issue for GISTIC so that can be tracked separately. Thanks!

**Comment by pageale** [comment]
Hello there !

This is the `.command.sh`, I attached it in the OP as txt since github did not support `.sh` extension.

```console
#!/bin/bash -euo pipefail
img2pdf  A_R_genome_plot.png B_R_genome_plot.png C_R_genome_plot.png D_R_genome_plot.png \
    --title "WisecondorX results" \
    -o genome_plots.pdf

cat <<-END_VERSIONS > versions.yml
"DINCALCILAB_SAMURAI:SAMURAI:LIQUID_BIOPSY:CONVERT_WISECONDORX_IMAGES":
    img2pdf: $(img2pdf --version | cut -d' ' -f2)
END_VERSIONS
                                                                             
```

Thanks !

**Comment by lbeltrame** [comment]
Now *this*is truly weird. Are you using Docker, I assume?
What if you run just Docker in that folder with 

```
docker run -v $(pwd):/data quay.io/einar_rainhart/img2pdf:latest 'cd /data && ./.command.sh
```

Does it still error out?

**Comment by lbeltrame** [comment]
*After* testing like I suggested, you might want to update: I changed the container to use Seqera's Wave service and hopefully it might be better.

**Comment by pageale** [comment]
Hello ! Yes, the new version coorect it and the `genome_ploy.pdf` is created without problem !  Thank you so much !

**Comment by lbeltrame** [comment]
Great! I'll close this and tag a new release with the fix. Thanks a bunch for your feedback!
